#!/bin/bash
chmod +x spearscripts/rad-1.sh
chmod +x spearscripts/rad-2.sh
chmod +x spearscripts/rad-3.sh
chmod +x spearscripts/rad-4.sh
chmod +x spearscripts/rad-5.sh
chmod +x spearscripts/rad-6.sh
chmod +x spearscripts/rad-7.sh
chmod +x spearscripts/rad-8.sh
chmod +x spearscripts/rad-9.sh
chmod +x spearscripts/rad-10.sh
chmod +x spearscripts/rad-11.sh
chmod +x spearscripts/rad-12.sh
chmod +x spearscripts/rad-13.sh
chmod +x spearscripts/rad-14.sh
chmod +x spearscripts/rad-15.sh
chmod +x spearscripts/rad-16.sh
chmod +x spearscripts/rad-17.sh
chmod +x spearscripts/rad-18.sh
chmod +x spearscripts/rad-19.sh
chmod +x spearscripts/rad-20.sh
chmod +x spearscripts/rad-21.sh
chmod +x spearscripts/rad-22.sh
chmod +x spearscripts/rad-23.sh
chmod +x spearscripts/rad-24.sh
chmod +x spearscripts/rad-25.sh
chmod +x spearscripts/rad-26.sh
chmod +x spearscripts/rad-27.sh
chmod +x spearscripts/rad-28.sh
chmod +x spearscripts/rad-29.sh
chmod +x spearscripts/rad-30.sh
chmod +x spearscripts/rad-31.sh
chmod +x spearscripts/rad-32.sh
chmod +x spearscripts/rad-33.sh
chmod +x spearscripts/rad-34.sh
chmod +x spearscripts/rad-35.sh
chmod +x spearscripts/rad-36.sh
chmod +x spearscripts/rad-37.sh
chmod +x spearscripts/rad-38.sh
chmod +x spearscripts/rad-39.sh
chmod +x spearscripts/rad-40.sh
chmod +x spearscripts/rad-41.sh
chmod +x spearscripts/rad-42.sh
chmod +x spearscripts/rad-43.sh
chmod +x spearscripts/rad-44.sh
chmod +x spearscripts/rad-45.sh
chmod +x spearscripts/rad-46.sh
chmod +x spearscripts/rad-47.sh
chmod +x spearscripts/rad-48.sh
chmod +x spearscripts/rad-49.sh
chmod +x spearscripts/rad-50.sh
chmod +x spear/uninstall.sh